/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jctools.queues.unpadded;
import org.jctools.util.InternalAPI;
import static org.jctools.util.UnsafeLongArrayAccess.*;
import org.jctools.queues.*;



/**
 * NOTE: This class was automatically generated by org.jctools.queues.unpadded.JavaParsingUnpaddedQueueGenerator
 * which can found in the jctools-build module. The original source file is MpmcUnboundedXaddChunk.java.
 */
@InternalAPI
public final class MpmcUnboundedXaddUnpaddedChunk<E> extends MpUnboundedXaddUnpaddedChunk<MpmcUnboundedXaddUnpaddedChunk<E>, E>
{
    private final long[] sequence;

    public MpmcUnboundedXaddUnpaddedChunk(long index, MpmcUnboundedXaddUnpaddedChunk<E> prev, int size, boolean pooled)
    {
        super(index, prev, size, pooled);
        if (pooled)
        {
            sequence = allocateLongArray(size);
            for (int i = 0; i < size; i++)
            {
                soLongElement(sequence, calcLongElementOffset(i), NOT_USED);
            }
        }
        else
        {
            sequence = null;
        }
    }

    public void soSequence(int index, long e)
    {
        assert isPooled();
        soLongElement(sequence, calcLongElementOffset(index), e);
    }

    public long lvSequence(int index)
    {
        assert isPooled();
        return lvLongElement(sequence, calcLongElementOffset(index));
    }

    public void spinForSequence(int index, long e)
    {
        assert isPooled();
        final long[] sequence = this.sequence;
        final long offset = calcLongElementOffset(index);
        while (true)
        {
            if (lvLongElement(sequence, offset) == e)
            {
                break;
            }
        }
    }
}
