/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jctools.queues.unpadded;

import org.jctools.util.InternalAPI;
import org.jctools.queues.*;

/**
 * NOTE: This class was automatically generated by org.jctools.queues.unpadded.JavaParsingUnpaddedQueueGenerator
 * which can found in the jctools-build module. The original source file is MpscUnboundedXaddChunk.java.
 */
@InternalAPI
public final class MpscUnboundedXaddUnpaddedChunk<E> extends MpUnboundedXaddUnpaddedChunk<MpscUnboundedXaddUnpaddedChunk<E>, E> {

    public MpscUnboundedXaddUnpaddedChunk(long index, MpscUnboundedXaddUnpaddedChunk<E> prev, int size, boolean pooled) {
        super(index, prev, size, pooled);
    }
}
