package org.jctools.queues.util;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.Node;
import com.github.javaparser.ast.NodeList;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.FieldDeclaration;
import com.github.javaparser.ast.body.VariableDeclarator;
import com.github.javaparser.ast.comments.Comment;
import com.github.javaparser.ast.expr.AnnotationExpr;
import com.github.javaparser.ast.expr.VariableDeclarationExpr;
import com.github.javaparser.ast.nodeTypes.NodeWithType;
import com.github.javaparser.ast.type.ArrayType;
import com.github.javaparser.ast.type.ClassOrInterfaceType;
import com.github.javaparser.ast.type.Type;
import com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter;

import java.io.File;
import java.io.FileWriter;

public class GeneratorUtils {

    /**
     * Remove padding fields from the given class.
     */
    public static void cleanupPaddingComments(CompilationUnit cu)
    {
        for (Comment comment : cu.getAllContainedComments())
        {
            String content = comment.getContent();
            if (content.contains("byte b") || content.contains("drop 8b") || content.contains("drop 16b") ) {
                comment.remove();
            }
        }
    }

    /**
     * Remove padding fields from the given class.
     */
    public static void removePaddingFields(ClassOrInterfaceDeclaration node) {
        // remove padding fields
        for (FieldDeclaration field : node.getFields())
        {
            String fieldName = field.getVariables().get(0).getNameAsString();
            if (fieldName.startsWith("b0") || fieldName.startsWith("b1")) {
                node.remove(field);
            }
        }
    }

    /**
     * Build a generator instance of the given class with the given file name.
     */
    public static <T> T buildGenerator(Class<? extends T> generatorClass, String fileName) throws Exception {
        return generatorClass.getDeclaredConstructor(String.class).newInstance(fileName);
    }

    private static final String INDENT_LEVEL = "    ";

    /**
     * Format a multiline javadoc comment with the given lines and indentation level.
     */
    public static String formatMultilineJavadoc(int indent, String... lines) {
        String indentation = "";
        for (int i = 0; i < indent; i++) {
            indentation += INDENT_LEVEL;
        }

        String out = "\n";
        for (String line : lines) {
            out += indentation + " * " + line + "\n";
        }
        out += indentation + " ";
        return out;
    }

    /**
     * Prepend a "this class was generated by..." Javadoc to {@code node}, preserving any existing
     * Javadoc beneath a properly-formatted blank-line separator.
     * <p>
     * When pre-existing Javadoc is present, the merged Javadoc inserts a {@code  *} bridge line
     * between the generator note and the original content; without the asterisk the blank line
     * renders as a stray space-only line that breaks the Javadoc block visually.
     */
    public static void prependGeneratedNoteJavadoc(
            com.github.javaparser.ast.nodeTypes.NodeWithJavadoc<?> node,
            Class<?> generatorClass,
            String sourceFileName) {
        String note = formatMultilineJavadoc(0,
                "NOTE: This class was automatically generated by " + generatorClass.getName(),
                "which can found in the jctools-build module. The original source file is " + sourceFileName + ".");
        String existing = node.getJavadocComment()
                .map(com.github.javaparser.ast.comments.JavadocComment::getContent)
                .orElse("");
        node.setJavadocComment(existing.isEmpty() ? note : note + "*" + existing);
    }

    /**
     * Renames a {@link ClassOrInterfaceType} by fully replacing it with a freshly-constructed type
     * that copies its scope, type arguments, and annotations. Works around a
     * {@link LexicalPreservingPrinter} bug where {@code type.setName(...)} doesn't propagate when
     * the type is hosted by a {@link VariableDeclarator} (so {@code Foo<E> x} keeps the original
     * {@code Foo} after a rename).
     */
    public static void renameType(ClassOrInterfaceType type, String newName) {
        ClassOrInterfaceType replacement = new ClassOrInterfaceType(
                type.getScope().map(s -> (ClassOrInterfaceType) s.clone()).orElse(null),
                newName);
        type.getTypeArguments().ifPresent(args -> {
            NodeList<Type> clonedArgs = new NodeList<>();
            for (Type ta : args) {
                clonedArgs.add(ta.clone());
            }
            replacement.setTypeArguments(clonedArgs);
        });
        for (AnnotationExpr ann : type.getAnnotations()) {
            replacement.addAnnotation(ann.clone());
        }
        type.replace(replacement);
    }

    /**
     * Replaces the type of a node holding one. Works around a {@link LexicalPreservingPrinter} bug
     * where replacing an {@link ArrayType} with a non-array type on a {@link VariableDeclarator}
     * leaves the original {@code []} brackets in the output (e.g. {@code E[] buffer} becomes
     * {@code AtomicReferenceArray<E>[] buffer} instead of {@code AtomicReferenceArray<E> buffer}).
     * <p>
     * The brackets are tracked by LPP at the {@link VariableDeclarator} level rather than as part
     * of the {@link ArrayType} node, so {@code setType(...)} doesn't remove them. We work around
     * this by rebuilding the enclosing {@link FieldDeclaration} or {@link VariableDeclarationExpr}
     * with a freshly-constructed {@link VariableDeclarator}; freshly-constructed nodes have no
     * preservation data so LPP falls back to the default printer for them.
     */
    public static void replaceType(NodeWithType<?, Type> holder, Type newType) {
        Type oldType = holder.getType();
        boolean needsArrayWorkaround = holder instanceof VariableDeclarator
                && oldType instanceof ArrayType
                && !(newType instanceof ArrayType);
        if (!needsArrayWorkaround) {
            holder.setType(newType);
            return;
        }
        VariableDeclarator vd = (VariableDeclarator) holder;
        Node parent = vd.getParentNode().orElse(null);
        VariableDeclarator newVd = new VariableDeclarator(newType, vd.getName().clone(),
                vd.getInitializer().map(e -> (com.github.javaparser.ast.expr.Expression) e.clone()).orElse(null));
        if (parent instanceof FieldDeclaration) {
            FieldDeclaration fd = (FieldDeclaration) parent;
            FieldDeclaration replacement = new FieldDeclaration(
                    new NodeList<>(fd.getModifiers()),
                    new NodeList<>(fd.getAnnotations()),
                    new NodeList<>(newVd));
            fd.getJavadocComment().ifPresent(replacement::setJavadocComment);
            fd.getComment().ifPresent(replacement::setComment);
            fd.replace(replacement);
        } else if (parent instanceof VariableDeclarationExpr) {
            VariableDeclarationExpr vde = (VariableDeclarationExpr) parent;
            VariableDeclarationExpr replacement = new VariableDeclarationExpr(
                    new NodeList<>(vde.getModifiers()),
                    new NodeList<>(newVd));
            vde.getComment().ifPresent(replacement::setComment);
            vde.replace(replacement);
        } else {
            throw new IllegalStateException(
                    "VariableDeclarator with array type has unsupported parent kind " +
                    (parent == null ? "null" : parent.getClass().getName()) +
                    "; the LPP array-bracket workaround handles only FieldDeclaration and VariableDeclarationExpr.");
        }
    }

    public static void runJCToolsGenerator(Class<? extends JCToolsGenerator> generatorClass, String[] args) throws Exception {

        if (args.length < 2) {
            throw new IllegalArgumentException("Usage: outputDirectory inputSourceFiles");
        }

        File outputDirectory = new File(args[0]);

        for (int i = 1; i < args.length; i++) {
            File file = new File(args[i]);
            System.out.println("Processing " + file);
            CompilationUnit cu = parseSourceFile(file);
            JCToolsGenerator generator = buildGenerator(generatorClass, file.getName());
            String output = applyGenerator(generator, cu);

            String outputFileName = generator.translateQueueName(file.getName().replace(".java", "")) + ".java";
            try (FileWriter writer = new FileWriter(new File(outputDirectory, outputFileName))) {
                writer.write(output);
            }

            System.out.println("Saved to " + outputFileName);
        }
    }

    /**
     * Parse a Java source file via {@link JavaParser}, surfacing parse problems with the file name
     * rather than the bare {@link java.util.NoSuchElementException} that {@code getResult().get()}
     * throws on failure. JavaParser may return a salvaged-partial result for a malformed source
     * with non-empty {@code getProblems()}; we treat any reported problem as a hard failure since
     * the generator's downstream rewrites assume a well-formed AST.
     */
    static CompilationUnit parseSourceFile(File file) throws java.io.FileNotFoundException {
        com.github.javaparser.ParseResult<CompilationUnit> result = new JavaParser().parse(file);
        if (!result.getProblems().isEmpty() || !result.getResult().isPresent()) {
            throw new IllegalStateException(
                    "Failed to parse " + file + ": " + result.getProblems());
        }
        return result.getResult().get();
    }

    /**
     * Apply a generator to an already-parsed compilation unit and return the printed result.
     * <p>
     * Sets up {@link LexicalPreservingPrinter} before mutation so that comments and untouched
     * formatting are preserved across the visit/transform/import-organise/cleanup phases.
     */
    public static String applyGenerator(JCToolsGenerator generator, CompilationUnit cu) {
        LexicalPreservingPrinter.setup(cu);
        generator.visit(cu, null);
        generator.organiseImports(cu);
        generator.cleanupComments(cu);
        return LexicalPreservingPrinter.print(cu);
    }
}
