#!/usr/bin/env bash
#
# Compare every generated queue class produced by the codegen on two git refs
# and verify they are semantically equivalent — same fields and methods,
# bytecode identical modulo declaration order, static-init block ordering,
# whitespace, and comments.
#
# Usage:
#   check-codegen-semantics.sh [<base-ref> [<head-ref>]]
#
# Defaults: base = origin/master, head = HEAD.
#
# Each ref is checked out into a temporary git worktree, the build module's
# generators are run (mvn install -DskipTests), and the resulting .class files
# are compared with semcmp.py. Exits 0 if every class is semantically
# equivalent; non-zero with a list of offending classes otherwise.

set -euo pipefail

BASE_REF=${1:-origin/master}
HEAD_REF=${2:-HEAD}

REPO_ROOT=$(git rev-parse --show-toplevel)
SCRIPT_DIR=$REPO_ROOT/jctools-build/scripts
WORK=$(mktemp -d)
trap "rm -rf '$WORK'; git worktree remove --force '$WORK/before' 2>/dev/null || true; git worktree remove --force '$WORK/after' 2>/dev/null || true" EXIT

echo "==> Setting up worktrees"
git worktree add -f "$WORK/before" "$BASE_REF" >/dev/null
git worktree add -f "$WORK/after"  "$HEAD_REF" >/dev/null

build() {
    local where=$1
    echo "==> Generating + compiling in $where"
    (cd "$where" && mvn install -DskipTests -q)
}

build "$WORK/before"
build "$WORK/after"

echo "==> Comparing generated bytecode"
SAME=0; SEMI=0; FAIL=0
FAILED_FILES=()

# Generated queues live under: jctools-core/target/classes/org/jctools/queues/{atomic,unpadded}/**
# and: jctools-core-jdk11/target/classes/org/jctools/queues/varhandle/**
GENERATED_ROOTS=(
    "jctools-core/target/classes/org/jctools/queues/atomic"
    "jctools-core/target/classes/org/jctools/queues/unpadded"
    "jctools-core-jdk11/target/classes/org/jctools/queues/varhandle"
)

for root in "${GENERATED_ROOTS[@]}"; do
    [ -d "$WORK/before/$root" ] || continue
    while IFS= read -r cls; do
        rel=${cls#$WORK/before/}
        after=$WORK/after/$rel
        [ -f "$after" ] || continue
        if diff -q <(javap -p -c -constants "$cls" 2>/dev/null) \
                   <(javap -p -c -constants "$after" 2>/dev/null) >/dev/null; then
            SAME=$((SAME + 1))
        elif python3 "$SCRIPT_DIR/semcmp.py" "$cls" "$after" >/dev/null 2>&1; then
            SEMI=$((SEMI + 1))
        else
            FAIL=$((FAIL + 1))
            FAILED_FILES+=("$rel")
        fi
    done < <(find "$WORK/before/$root" -name '*.class')
done

echo
echo "==> Result"
echo "  raw-identical:                          $SAME"
echo "  semantically-identical (after canon):   $SEMI"
echo "  semantically-different:                 $FAIL"

if [ "$FAIL" -ne 0 ]; then
    echo
    echo "Classes with semantic differences:"
    for f in "${FAILED_FILES[@]}"; do
        echo "  $f"
        python3 "$SCRIPT_DIR/semcmp.py" \
            "$WORK/before/$f" "$WORK/after/$f" | head -20 | sed 's/^/    /'
        echo
    done
    exit 1
fi
