package org.jctools.queues.unpadded;

import java.util.ArrayList;
import java.util.List;

import com.github.javaparser.ast.*;
import com.github.javaparser.ast.body.*;
import com.github.javaparser.ast.comments.TraditionalJavadocComment;
import com.github.javaparser.ast.expr.ClassExpr;
import com.github.javaparser.ast.expr.Expression;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.expr.ObjectCreationExpr;
import com.github.javaparser.ast.nodeTypes.NodeWithType;
import com.github.javaparser.ast.type.ClassOrInterfaceType;
import com.github.javaparser.ast.type.Type;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import org.jctools.queues.util.JCToolsGenerator;

import static org.jctools.queues.util.GeneratorUtils.cleanupPaddingComments;
import static org.jctools.queues.util.GeneratorUtils.formatMultilineJavadoc;
import static org.jctools.queues.util.GeneratorUtils.removePaddingFields;
import static org.jctools.queues.util.GeneratorUtils.runJCToolsGenerator;

public class JavaParsingUnpaddedQueueGenerator extends VoidVisitorAdapter<Void> implements JCToolsGenerator {

    protected final String sourceFileName;

    public static void main(String[] args) throws Exception {
        runJCToolsGenerator(JavaParsingUnpaddedQueueGenerator.class, args);
    }

    public JavaParsingUnpaddedQueueGenerator(String sourceFileName) {
        this.sourceFileName = sourceFileName;
    }


    @Override
    public void cleanupComments(CompilationUnit cu) {
        cleanupPaddingComments(cu);
    }

    @Override
    public void organiseImports(CompilationUnit cu) {
        List<ImportDeclaration> importDecls = new ArrayList<>();
        for (ImportDeclaration importDeclaration : cu.getImports()) {
            String name = importDeclaration.getNameAsString();
            // Rewrite static imports from Chunk classes to point at the translated variant,
            // e.g. "import static o.j.q.MpmcUnboundedXaddChunk.NOT_USED" ->
            //      "import static o.j.q.unpadded.MpmcUnboundedXaddUnpaddedChunk.NOT_USED"
            if (importDeclaration.isStatic() && name.startsWith("org.jctools.queues.") && name.contains("Chunk.")) {
                String simpleName = name.substring(name.lastIndexOf('.') + 1);
                String className = name.substring("org.jctools.queues.".length(), name.lastIndexOf('.'));
                if (className.endsWith("Chunk")) {
                    String translatedClass = translateQueueName(className);
                    importDecls.add(new ImportDeclaration("org.jctools.queues.unpadded." + translatedClass + "." + simpleName, true, false));
                    continue;
                }
            }
            importDecls.add(importDeclaration);
        }
        cu.getImports().clear();
        for (ImportDeclaration importDecl : importDecls) {
            cu.addImport(importDecl);
        }
        cu.addImport(new ImportDeclaration("org.jctools.queues", false, true));
    }

    @Override
    public String translateQueueName(String qName) {
        if (qName.contains("LinkedQueue") || qName.contains("LinkedArrayQueue")) {
            return qName.replace("Linked", "LinkedUnpadded");
        }

        // ArrayQueue check must come before Chunk check because some inner hierarchy classes
        // contain both "ArrayQueue" and end with "Chunk" (e.g. MpUnboundedXaddArrayQueueProducerChunk)
        if (qName.contains("ArrayQueue")) {
            return qName.replace("ArrayQueue", "UnpaddedArrayQueue");
        }

        // Standalone Chunk classes (e.g. MpUnboundedXaddChunk -> MpUnboundedXaddUnpaddedChunk)
        if (qName.endsWith("Chunk")) {
            return qName.replace("Chunk", "UnpaddedChunk");
        }

        throw new IllegalArgumentException("Unexpected queue name: " + qName);

    }

    @Override
    public void visit(PackageDeclaration n, Void arg) {
        super.visit(n, arg);
        // Change the package of the output
        n.setName("org.jctools.queues.unpadded");
    }

    @Override
    public void visit(ClassOrInterfaceDeclaration node, Void arg) {
        super.visit(node, arg);
        String nameAsString = node.getNameAsString();
        if (!nameAsString.contains("Queue") && !nameAsString.endsWith("Chunk"))
            return;
        // fixup inheritance
        replaceParentClasses(node);
        // fixup name
        node.setName(translateQueueName(nameAsString));

        node.setJavadocComment(formatMultilineJavadoc(0,
            "NOTE: This class was automatically generated by "
                + this.getClass().getName(),
            "which can found in the jctools-build module. The original source file is " + sourceFileName + ".")
            + node.getJavadocComment().orElse(new TraditionalJavadocComment("")).getContent());

        removePaddingFields(node);
    }

    @Override
    public void visit(MethodCallExpr n, Void arg)
    {
        super.visit(n, arg);
        if (!n.getName().getIdentifier().equals("fieldOffset")) {
            return;
        }
        for (Expression argument : n.getArguments())
        {
            if (argument.isClassExpr()) {
                ClassExpr classExpr = argument.asClassExpr();
                String type = classExpr.getTypeAsString();
                if (!type.contains("Unpadded")) {
                    classExpr.setType(translateQueueName(type));
                }
            }
        }

    }

    /**
     * Renames Chunk type references (e.g. {@code MpUnboundedXaddChunk} to {@code MpUnboundedXaddUnpaddedChunk})
     * wherever they appear as types. The {@code contains("Unpadded")} guard prevents double-translation.
     */
    @Override
    public void visit(ClassOrInterfaceType n, Void arg) {
        super.visit(n, arg);
        String name = n.getNameAsString();
        if (name.endsWith("Chunk") && !name.contains("Unpadded")) {
            n.setName(translateQueueName(name));
        }
    }

    /**
     * Renames Chunk class references in name expressions, e.g. {@code MpmcUnboundedXaddChunk.NOT_USED}.
     * The {@code isUpperCase} check avoids renaming local variables like {@code cChunk}.
     */
    @Override
    public void visit(NameExpr n, Void arg) {
        super.visit(n, arg);
        String name = n.getNameAsString();
        if (name.endsWith("Chunk") && Character.isUpperCase(name.charAt(0)) && !name.contains("Unpadded")) {
            n.setName(translateQueueName(name));
        }
    }

    @Override
    public void visit(ConstructorDeclaration n, Void arg) {
        super.visit(n, arg);
        // Update the ctor to match the class name
        String nameAsString = n.getNameAsString();
        if (nameAsString.contains("Queue") || nameAsString.endsWith("Chunk"))
            n.setName(translateQueueName(nameAsString));
    }

    /**
     * Replaces {@code new SpscArrayQueue<R>(...)} with {@code new SpscUnpaddedArrayQueue<R>(...)}.
     * Used by xadd queues which pool chunks internally via SpscArrayQueue.
     */
    @Override
    public void visit(ObjectCreationExpr n, Void arg) {
        super.visit(n, arg);
        if (isRefType(n.getType(), "SpscArrayQueue")) {
            ClassOrInterfaceType newType = new ClassOrInterfaceType(null, "SpscUnpaddedArrayQueue");
            n.getType().getTypeArguments().ifPresent(newType::setTypeArguments);
            n.setType(newType);
        }
    }

    /** Replaces SpscArrayQueue type in variable declarations — same as {@link #visit(ObjectCreationExpr, Void)}. */
    @Override
    public void visit(VariableDeclarator n, Void arg) {
        super.visit(n, arg);
        if (isRefType(n.getType(), "SpscArrayQueue")) {
            ClassOrInterfaceType newType = new ClassOrInterfaceType(null, "SpscUnpaddedArrayQueue");
            if (n.getType() instanceof ClassOrInterfaceType) {
                ((ClassOrInterfaceType) n.getType()).getTypeArguments().ifPresent(newType::setTypeArguments);
            }
            n.setType(newType);
        }
    }

    /** Replaces SpscArrayQueue type in parameters — same as {@link #visit(ObjectCreationExpr, Void)}. */
    @Override
    public void visit(Parameter n, Void arg) {
        super.visit(n, arg);
        if (isRefType(n.getType(), "SpscArrayQueue")) {
            ClassOrInterfaceType newType = new ClassOrInterfaceType(null, "SpscUnpaddedArrayQueue");
            if (n.getType() instanceof ClassOrInterfaceType) {
                ((ClassOrInterfaceType) n.getType()).getTypeArguments().ifPresent(newType::setTypeArguments);
            }
            n.setType(newType);
        }
    }

    protected boolean isRefType(Type in, String className) {
        if (in instanceof ClassOrInterfaceType) {
            return className.equals(((ClassOrInterfaceType) in).getNameAsString());
        }
        return false;
    }

    /**
     * Searches all extended or implemented super classes or interfaces for
     * special classes that differ with the atomics version and replaces them
     * with the appropriate class.
     */
    protected void replaceParentClasses(ClassOrInterfaceDeclaration n) {
        for (ClassOrInterfaceType parent : n.getExtendedTypes()) {
            String parentNameAsString = parent.getNameAsString();
            switch (parentNameAsString) {
                case "AbstractQueue":
                    // ignore the JDK parent
                    break;
                default:
                    // Guard against double-translation: visit(ClassOrInterfaceType) may have
                    // already renamed this type before we get here
                    if (!parentNameAsString.contains("Unpadded")) {
                        parent.setName(translateQueueName(parentNameAsString));
                    }
            }
        }
    }
}
