/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jctools.queues.varhandle.unpadded;

import java.lang.invoke.MethodHandles;
import java.lang.invoke.VarHandle;
import org.jctools.queues.*;
import static org.jctools.queues.varhandle.VarHandleQueueUtil.*;
import org.jctools.queues.varhandle.VarHandleReferenceArrayQueue;
import org.jctools.queues.varhandle.SequencedVarHandleReferenceArrayQueue;

/**
 * NOTE: This class was automatically generated by org.jctools.queues.varhandle.unpadded.JavaParsingVarHandleUnpaddedArrayQueueGenerator
 * which can found in the jctools-build module. The original source file is SpmcArrayQueue.java.
 */
abstract class SpmcVarHandleUnpaddedArrayQueueL1Pad<E> extends VarHandleReferenceArrayQueue<E> {

    SpmcVarHandleUnpaddedArrayQueueL1Pad(int capacity) {
        super(capacity);
    }
}

/**
 * NOTE: This class was automatically generated by org.jctools.queues.varhandle.unpadded.JavaParsingVarHandleUnpaddedArrayQueueGenerator
 * which can found in the jctools-build module. The original source file is SpmcArrayQueue.java.
 */
abstract class SpmcVarHandleUnpaddedArrayQueueProducerIndexField<E> extends SpmcVarHandleUnpaddedArrayQueueL1Pad<E> {

    private static final VarHandle VH_PRODUCER_INDEX;

    static {
        try {
            VH_PRODUCER_INDEX = MethodHandles.lookup().findVarHandle(SpmcVarHandleUnpaddedArrayQueueProducerIndexField.class, "producerIndex", long.class);
        } catch (Exception e) {
            throw new ExceptionInInitializerError(e);
        }
    }

    private volatile long producerIndex;

    SpmcVarHandleUnpaddedArrayQueueProducerIndexField(int capacity) {
        super(capacity);
    }

    @Override
    public final long lvProducerIndex() {
        return (long) VH_PRODUCER_INDEX.getVolatile(this);
    }

    final long lpProducerIndex() {
        return producerIndex;
    }

    final void soProducerIndex(long newValue) {
        VH_PRODUCER_INDEX.setRelease(this, newValue);
    }

    final long laProducerIndex() {
        return (long) VH_PRODUCER_INDEX.getAcquire(this);
    }
}

/**
 * NOTE: This class was automatically generated by org.jctools.queues.varhandle.unpadded.JavaParsingVarHandleUnpaddedArrayQueueGenerator
 * which can found in the jctools-build module. The original source file is SpmcArrayQueue.java.
 */
abstract class SpmcVarHandleUnpaddedArrayQueueL2Pad<E> extends SpmcVarHandleUnpaddedArrayQueueProducerIndexField<E> {

    SpmcVarHandleUnpaddedArrayQueueL2Pad(int capacity) {
        super(capacity);
    }
}

/**
 * NOTE: This class was automatically generated by org.jctools.queues.varhandle.unpadded.JavaParsingVarHandleUnpaddedArrayQueueGenerator
 * which can found in the jctools-build module. The original source file is SpmcArrayQueue.java.
 */
abstract class SpmcVarHandleUnpaddedArrayQueueConsumerIndexField<E> extends SpmcVarHandleUnpaddedArrayQueueL2Pad<E> {

    private static final VarHandle VH_CONSUMER_INDEX;

    static {
        try {
            VH_CONSUMER_INDEX = MethodHandles.lookup().findVarHandle(SpmcVarHandleUnpaddedArrayQueueConsumerIndexField.class, "consumerIndex", long.class);
        } catch (Exception e) {
            throw new ExceptionInInitializerError(e);
        }
    }

    private volatile long consumerIndex;

    SpmcVarHandleUnpaddedArrayQueueConsumerIndexField(int capacity) {
        super(capacity);
    }

    @Override
    public final long lvConsumerIndex() {
        return (long) VH_CONSUMER_INDEX.getVolatile(this);
    }

    final boolean casConsumerIndex(long expect, long newValue) {
        return VH_CONSUMER_INDEX.compareAndSet(this, expect, newValue);
    }

    final long laConsumerIndex() {
        return (long) VH_CONSUMER_INDEX.getAcquire(this);
    }
}

/**
 * NOTE: This class was automatically generated by org.jctools.queues.varhandle.unpadded.JavaParsingVarHandleUnpaddedArrayQueueGenerator
 * which can found in the jctools-build module. The original source file is SpmcArrayQueue.java.
 */
abstract class SpmcVarHandleUnpaddedArrayQueueMidPad<E> extends SpmcVarHandleUnpaddedArrayQueueConsumerIndexField<E> {

    SpmcVarHandleUnpaddedArrayQueueMidPad(int capacity) {
        super(capacity);
    }
}

/**
 * NOTE: This class was automatically generated by org.jctools.queues.varhandle.unpadded.JavaParsingVarHandleUnpaddedArrayQueueGenerator
 * which can found in the jctools-build module. The original source file is SpmcArrayQueue.java.
 */
abstract class SpmcVarHandleUnpaddedArrayQueueProducerIndexCacheField<E> extends SpmcVarHandleUnpaddedArrayQueueMidPad<E> {

    private static final VarHandle VH_PRODUCER_INDEX_CACHE;

    static {
        try {
            VH_PRODUCER_INDEX_CACHE = MethodHandles.lookup().findVarHandle(SpmcVarHandleUnpaddedArrayQueueProducerIndexCacheField.class, "producerIndexCache", long.class);
        } catch (Exception e) {
            throw new ExceptionInInitializerError(e);
        }
    }

    // This is separated from the consumerIndex which will be highly contended in the hope that this value spends most
    // of it's time in a cache line that is Shared(and rarely invalidated)
    private volatile long producerIndexCache;

    SpmcVarHandleUnpaddedArrayQueueProducerIndexCacheField(int capacity) {
        super(capacity);
    }

    protected final long lvProducerIndexCache() {
        return (long) VH_PRODUCER_INDEX_CACHE.getVolatile(this);
    }

    protected final void svProducerIndexCache(long newValue) {
        producerIndexCache = newValue;
    }

    final long laProducerIndexCache() {
        return (long) VH_PRODUCER_INDEX_CACHE.getAcquire(this);
    }
}

/**
 * NOTE: This class was automatically generated by org.jctools.queues.varhandle.unpadded.JavaParsingVarHandleUnpaddedArrayQueueGenerator
 * which can found in the jctools-build module. The original source file is SpmcArrayQueue.java.
 */
abstract class SpmcVarHandleUnpaddedArrayQueueL3Pad<E> extends SpmcVarHandleUnpaddedArrayQueueProducerIndexCacheField<E> {

    SpmcVarHandleUnpaddedArrayQueueL3Pad(int capacity) {
        super(capacity);
    }
}

/**
 * NOTE: This class was automatically generated by org.jctools.queues.varhandle.unpadded.JavaParsingVarHandleUnpaddedArrayQueueGenerator
 * which can found in the jctools-build module. The original source file is SpmcArrayQueue.java.
 */
public class SpmcVarHandleUnpaddedArrayQueue<E> extends SpmcVarHandleUnpaddedArrayQueueL3Pad<E> {

    public SpmcVarHandleUnpaddedArrayQueue(final int capacity) {
        super(capacity);
    }

    @Override
    public boolean offer(final E e) {
        if (null == e) {
            throw new NullPointerException();
        }
        final E[] buffer = this.buffer;
        final int mask = this.mask;
        final long currProducerIndex = laProducerIndex();
        final int offset = calcCircularRefElementOffset(currProducerIndex, mask);
        if (null != lvRefElement(buffer, offset)) {
            long size = currProducerIndex - laConsumerIndex();
            if (size > mask) {
                return false;
            } else {
                // Bubble: This can happen because `poll` moves index before placing element.
                // spin wait for slot to clear, buggers wait freedom
                while (null != lvRefElement(buffer, offset)) {
                    // BURN
                }
            }
        }
        soRefElement(buffer, offset, e);
        // single producer, so store ordered is valid. It is also required to correctly publish the element
        // and for the consumers to pick up the tail value.
        soProducerIndex(currProducerIndex + 1);
        return true;
    }

    @Override
    public E poll() {
        long currentConsumerIndex;
        long currProducerIndexCache = lvProducerIndexCache();
        do {
            currentConsumerIndex = laConsumerIndex();
            if (currentConsumerIndex >= currProducerIndexCache) {
                long currProducerIndex = laProducerIndex();
                if (currentConsumerIndex >= currProducerIndex) {
                    return null;
                } else {
                    currProducerIndexCache = currProducerIndex;
                    svProducerIndexCache(currProducerIndex);
                }
            }
        } while (!casConsumerIndex(currentConsumerIndex, currentConsumerIndex + 1));
        // consumers are gated on latest visible tail, and so can't see a null value in the queue or overtake
        // and wrap to hit same location.
        return removeElement(buffer, currentConsumerIndex, mask);
    }

    private E removeElement(final E[] buffer, long index, final int mask) {
        final int offset = calcCircularRefElementOffset(index, mask);
        // load plain, element happens before it's index becomes visible
        final E e = lpRefElement(buffer, offset);
        // store ordered, make sure nulling out is visible. Producer is waiting for this value.
        soRefElement(buffer, offset, null);
        return e;
    }

    @Override
    public E peek() {
        final E[] buffer = this.buffer;
        final int mask = this.mask;
        long currProducerIndexCache = lvProducerIndexCache();
        long currentConsumerIndex;
        long nextConsumerIndex = laConsumerIndex();
        E e;
        do {
            currentConsumerIndex = nextConsumerIndex;
            if (currentConsumerIndex >= currProducerIndexCache) {
                long currProducerIndex = laProducerIndex();
                if (currentConsumerIndex >= currProducerIndex) {
                    return null;
                } else {
                    currProducerIndexCache = currProducerIndex;
                    svProducerIndexCache(currProducerIndex);
                }
            }
            e = lvRefElement(buffer, calcCircularRefElementOffset(currentConsumerIndex, mask));
            // sandwich the element load between 2 consumer index loads
            nextConsumerIndex = laConsumerIndex();
        } while (null == e || nextConsumerIndex != currentConsumerIndex);
        return e;
    }

    @Override
    public boolean relaxedOffer(E e) {
        if (null == e) {
            throw new NullPointerException("Null is not a valid element");
        }
        final E[] buffer = this.buffer;
        final int mask = this.mask;
        final long producerIndex = lpProducerIndex();
        final int offset = calcCircularRefElementOffset(producerIndex, mask);
        if (null != lvRefElement(buffer, offset)) {
            return false;
        }
        soRefElement(buffer, offset, e);
        // single producer, so store ordered is valid. It is also required to correctly publish the element
        // and for the consumers to pick up the tail value.
        soProducerIndex(producerIndex + 1);
        return true;
    }

    @Override
    public E relaxedPoll() {
        return poll();
    }

    @Override
    public E relaxedPeek() {
        final E[] buffer = this.buffer;
        final int mask = this.mask;
        long currentConsumerIndex;
        long nextConsumerIndex = laConsumerIndex();
        E e;
        do {
            currentConsumerIndex = nextConsumerIndex;
            e = lvRefElement(buffer, calcCircularRefElementOffset(currentConsumerIndex, mask));
            // sandwich the element load between 2 consumer index loads
            nextConsumerIndex = laConsumerIndex();
        } while (nextConsumerIndex != currentConsumerIndex);
        return e;
    }

    @Override
    public int drain(final Consumer<E> c, final int limit) {
        if (null == c)
            throw new IllegalArgumentException("c is null");
        if (limit < 0)
            throw new IllegalArgumentException("limit is negative: " + limit);
        if (limit == 0)
            return 0;
        final E[] buffer = this.buffer;
        final int mask = this.mask;
        long currProducerIndexCache = lvProducerIndexCache();
        int adjustedLimit = 0;
        long currentConsumerIndex;
        do {
            currentConsumerIndex = laConsumerIndex();
            // is there any space in the queue?
            if (currentConsumerIndex >= currProducerIndexCache) {
                long currProducerIndex = laProducerIndex();
                if (currentConsumerIndex >= currProducerIndex) {
                    return 0;
                } else {
                    currProducerIndexCache = currProducerIndex;
                    svProducerIndexCache(currProducerIndex);
                }
            }
            // try and claim up to 'limit' elements in one go
            int remaining = (int) (currProducerIndexCache - currentConsumerIndex);
            adjustedLimit = Math.min(remaining, limit);
        } while (!casConsumerIndex(currentConsumerIndex, currentConsumerIndex + adjustedLimit));
        for (int i = 0; i < adjustedLimit; i++) {
            c.accept(removeElement(buffer, currentConsumerIndex + i, mask));
        }
        return adjustedLimit;
    }

    @Override
    public int fill(final Supplier<E> s, final int limit) {
        if (null == s)
            throw new IllegalArgumentException("supplier is null");
        if (limit < 0)
            throw new IllegalArgumentException("limit is negative:" + limit);
        if (limit == 0)
            return 0;
        final E[] buffer = this.buffer;
        final int mask = this.mask;
        long producerIndex = this.lpProducerIndex();
        for (int i = 0; i < limit; i++) {
            final int offset = calcCircularRefElementOffset(producerIndex, mask);
            if (null != lvRefElement(buffer, offset)) {
                return i;
            }
            producerIndex++;
            soRefElement(buffer, offset, s.get());
            // ordered store -> atomic and ordered for size()
            soProducerIndex(producerIndex);
        }
        return limit;
    }

    @Override
    public int drain(final Consumer<E> c) {
        return MessagePassingQueueUtil.drain(this, c);
    }

    @Override
    public int fill(final Supplier<E> s) {
        return fill(s, capacity());
    }

    @Override
    public void drain(final Consumer<E> c, final WaitStrategy w, final ExitCondition exit) {
        MessagePassingQueueUtil.drain(this, c, w, exit);
    }

    @Override
    public void fill(final Supplier<E> s, final WaitStrategy w, final ExitCondition e) {
        MessagePassingQueueUtil.fill(this, s, w, e);
    }
}
