/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jctools.queues.atomic;

import org.jctools.util.InternalAPI;
import java.util.concurrent.atomic.*;
import org.jctools.queues.*;
import static org.jctools.queues.atomic.AtomicQueueUtil.*;

/**
 * NOTE: This class was automatically generated by org.jctools.queues.atomic.JavaParsingAtomicArrayQueueGenerator
 * which can found in the jctools-build module. The original source file is MpmcUnboundedXaddChunk.java.
 */
@InternalAPI
public final class MpmcUnboundedXaddAtomicChunk<E> extends MpUnboundedXaddAtomicChunk<MpmcUnboundedXaddAtomicChunk<E>, E> {

    private final AtomicLongArray sequence;

    public MpmcUnboundedXaddAtomicChunk(long index, MpmcUnboundedXaddAtomicChunk<E> prev, int size, boolean pooled) {
        super(index, prev, size, pooled);
        if (pooled) {
            sequence = allocateLongArray(size);
            for (int i = 0; i < size; i++) {
                soLongElement(sequence, calcLongElementOffset(i), NOT_USED);
            }
        } else {
            sequence = null;
        }
    }

    public void soSequence(int index, long e) {
        assert isPooled();
        soLongElement(sequence, calcLongElementOffset(index), e);
    }

    public long lvSequence(int index) {
        assert isPooled();
        return lvLongElement(sequence, calcLongElementOffset(index));
    }

    public void spinForSequence(int index, long e) {
        assert isPooled();
        final AtomicLongArray sequence = this.sequence;
        final int offset = calcLongElementOffset(index);
        while (true) {
            if (lvLongElement(sequence, offset) == e) {
                break;
            }
        }
    }
}
