package org.jctools.queues.atomic;

import org.jctools.util.InternalAPI;
import java.util.concurrent.atomic.*;
import org.jctools.queues.*;
import static org.jctools.queues.atomic.AtomicQueueUtil.*;

/**
 * NOTE: This class was automatically generated by org.jctools.queues.atomic.JavaParsingAtomicArrayQueueGenerator
 * which can found in the jctools-build module. The original source file is MpUnboundedXaddChunk.java.
 */
@InternalAPI
public class MpUnboundedXaddAtomicChunk<R, E> {

    private static final AtomicReferenceFieldUpdater<MpUnboundedXaddAtomicChunk, Object> NEXT_UPDATER = AtomicReferenceFieldUpdater.newUpdater(MpUnboundedXaddAtomicChunk.class, Object.class, "next");

    private static final AtomicLongFieldUpdater<MpUnboundedXaddAtomicChunk> INDEX_UPDATER = AtomicLongFieldUpdater.newUpdater(MpUnboundedXaddAtomicChunk.class, "index");

    private static final AtomicReferenceFieldUpdater<MpUnboundedXaddAtomicChunk, Object> PREV_UPDATER = AtomicReferenceFieldUpdater.newUpdater(MpUnboundedXaddAtomicChunk.class, Object.class, "prev");

    public final static int NOT_USED = -1;

    private final boolean pooled;

    private final AtomicReferenceArray<E> buffer;

    private volatile R prev;

    private volatile long index;

    private volatile R next;

    protected MpUnboundedXaddAtomicChunk(long index, R prev, int size, boolean pooled) {
        buffer = allocateRefArray(size);
        // next is null
        soPrev(prev);
        spIndex(index);
        this.pooled = pooled;
    }

    public final boolean isPooled() {
        return pooled;
    }

    public final long lvIndex() {
        return index;
    }

    public final void soIndex(long index) {
        INDEX_UPDATER.lazySet(this, index);
    }

    final void spIndex(long index) {
        INDEX_UPDATER.lazySet(this, index);
    }

    public final R lvNext() {
        return next;
    }

    public final void soNext(R value) {
        NEXT_UPDATER.lazySet(this, value);
    }

    public final R lvPrev() {
        return prev;
    }

    public final void soPrev(R value) {
        PREV_UPDATER.lazySet(this, value);
    }

    public final void soElement(int index, E e) {
        soRefElement(buffer, calcRefElementOffset(index), e);
    }

    public final E lvElement(int index) {
        return lvRefElement(buffer, calcRefElementOffset(index));
    }

    public final E spinForElement(int index, boolean isNull) {
        AtomicReferenceArray<E> buffer = this.buffer;
        int offset = calcRefElementOffset(index);
        E e;
        do {
            e = lvRefElement(buffer, offset);
        } while (isNull != (e == null));
        return e;
    }
}
