/*
 * Licensed under the Apache License, Version 2.0.
 */
package org.jctools.queues.atomic;
import java.util.AbstractQueue;
import java.util.concurrent.atomic.*;
import org.jctools.queues.*;
import static org.jctools.queues.atomic.AtomicQueueUtil.*;



/**
 * NOTE: This class was automatically generated by org.jctools.queues.atomic.JavaParsingAtomicLinkedQueueGenerator
 * which can found in the jctools-build module. The original source file is MpscLinkedQueue.java.
 *
 * Synthetic MPSC linked queue exercising the atomic-linked generator's full feature set,
 * mirroring the real MpscLinkedQueue (public/concrete with a public no-arg ctor).
 */
public class MpscLinkedAtomicQueue<E> extends BaseLinkedAtomicQueue<E>
{
    public MpscLinkedAtomicQueue()
    {
    }

    public static <E> MpscLinkedQueue<E> newMpscLinkedQueue()
    {
        return null;
    }

    @Override
    public boolean offer(final E e)
    {
        if (null == e)
        {
            throw new NullPointerException();
        }
        final LinkedQueueAtomicNode<E> nextNode = new LinkedQueueAtomicNode<E>(e);
        final LinkedQueueAtomicNode<E> prevProducerNode = xchgProducerNode(nextNode);
        prevProducerNode.soNext(nextNode);
        return true;
    }
}

/**
 * NOTE: This class was automatically generated by org.jctools.queues.atomic.JavaParsingAtomicLinkedQueueGenerator
 * which can found in the jctools-build module. The original source file is MpscLinkedQueue.java.
 */
abstract class BaseLinkedAtomicQueueProducerNodeRef<E> extends AbstractQueue<E>
{
    private static final AtomicReferenceFieldUpdater<BaseLinkedAtomicQueueProducerNodeRef, LinkedQueueAtomicNode> P_NODE_UPDATER = AtomicReferenceFieldUpdater.newUpdater(BaseLinkedAtomicQueueProducerNodeRef.class, LinkedQueueAtomicNode.class, "producerNode");
    
    private volatile LinkedQueueAtomicNode<E> producerNode;

    protected final LinkedQueueAtomicNode<E> lvProducerNode()
    {
        return producerNode;
    }

    protected final boolean casProducerNode(LinkedQueueAtomicNode<E> expect, LinkedQueueAtomicNode<E> newValue)
    {
        return P_NODE_UPDATER.compareAndSet(this, expect, newValue);
    }

    protected final void soProducerNode(LinkedQueueAtomicNode<E> newValue)
    {
        P_NODE_UPDATER.lazySet(this, newValue);
    }

    protected final LinkedQueueAtomicNode<E> lpProducerNode()
    {
        return producerNode;
    }
    
    protected final LinkedQueueAtomicNode<E> xchgProducerNode(LinkedQueueAtomicNode<E> newValue) {
        return P_NODE_UPDATER.getAndSet(this, newValue);
    }
}
