/*
 * Licensed under the Apache License, Version 2.0.
 */
package org.jctools.queues.unpadded;
import static org.jctools.util.UnsafeAccess.UNSAFE;
import static org.jctools.util.UnsafeAccess.fieldOffset;
import static org.jctools.util.UnsafeRefArrayAccess.*;
import org.jctools.queues.*;


/**
 * NOTE: This class was automatically generated by org.jctools.queues.unpadded.JavaParsingUnpaddedQueueGenerator
 * which can found in the jctools-build module. The original source file is GoldenSampleArrayQueue.java.
 */
abstract class GoldenSampleUnpaddedArrayQueueColdField<E> extends ConcurrentCircularUnpaddedArrayQueue<E>
{
    final int lookAheadStep;

    GoldenSampleUnpaddedArrayQueueColdField(int capacity)
    {
        super(capacity);
        lookAheadStep = capacity / 4;
    }
}

/**
 * NOTE: This class was automatically generated by org.jctools.queues.unpadded.JavaParsingUnpaddedQueueGenerator
 * which can found in the jctools-build module. The original source file is GoldenSampleArrayQueue.java.
 */
abstract class GoldenSampleUnpaddedArrayQueueL1Pad<E> extends GoldenSampleUnpaddedArrayQueueColdField<E>
{
    GoldenSampleUnpaddedArrayQueueL1Pad(int capacity)
    {
        super(capacity);
    }
}

/**
 * NOTE: This class was automatically generated by org.jctools.queues.unpadded.JavaParsingUnpaddedQueueGenerator
 * which can found in the jctools-build module. The original source file is GoldenSampleArrayQueue.java.
 */
abstract class GoldenSampleUnpaddedArrayQueueProducerIndexFields<E> extends GoldenSampleUnpaddedArrayQueueL1Pad<E>
{
    private final static long P_INDEX_OFFSET =
            fieldOffset(GoldenSampleUnpaddedArrayQueueProducerIndexFields.class, "producerIndex");

    private long producerIndex;
    protected long producerLimit;

    GoldenSampleUnpaddedArrayQueueProducerIndexFields(int capacity)
    {
        super(capacity);
    }

    @Override
    public final long lvProducerIndex()
    {
        return UNSAFE.getLongVolatile(this, P_INDEX_OFFSET);
    }

    final long lpProducerIndex()
    {
        return producerIndex;
    }

    final void soProducerIndex(final long newValue)
    {
        UNSAFE.putOrderedLong(this, P_INDEX_OFFSET, newValue);
    }

    final boolean casProducerIndex(long expect, long newValue)
    {
        return UNSAFE.compareAndSwapLong(this, P_INDEX_OFFSET, expect, newValue);
    }
}

/**
 * NOTE: This class was automatically generated by org.jctools.queues.unpadded.JavaParsingUnpaddedQueueGenerator
 * which can found in the jctools-build module. The original source file is GoldenSampleArrayQueue.java.
 *
 * Pre-existing Javadoc on the public class — the generator must prepend its NOTE without
 * dropping this content.
 */
public class GoldenSampleUnpaddedArrayQueue<E> extends GoldenSampleUnpaddedArrayQueueProducerIndexFields<E>
{
    static int sentinel;
    // Unrelated static initializer — must survive the Unsafe-cleanup pass.
    static
    {
        sentinel = 42;
    }

    public GoldenSampleUnpaddedArrayQueue(final int capacity)
    {
        super(capacity);
    }

    @Override
    public boolean offer(final E e)
    {
        if (null == e)
        {
            throw new NullPointerException();
        }
        final E[] buffer = this.buffer;
        final long mask = this.mask;
        final long pIndex = this.lpProducerIndex();
        final long offset = calcCircularRefElementOffset(pIndex, mask);
        soRefElement(buffer, offset, e);
        soProducerIndex(pIndex + 1);
        return true;
    }

    @Override
    public E poll()
    {
        return null;
    }

    public final int failFastOffer(final E e)
    {
        return 0;
    }

    // $gen:ignore
    public void debugDump()
    {
    }
}
