/*
 * Licensed under the Apache License, Version 2.0.
 */
package org.jctools.queues.varhandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.VarHandle;
import org.jctools.queues.*;
import static org.jctools.queues.varhandle.VarHandleQueueUtil.*;


/**
 * NOTE: This class was automatically generated by org.jctools.queues.varhandle.JavaParsingVarHandleArrayQueueGenerator
 * which can found in the jctools-build module. The original source file is GoldenSampleArrayQueue.java.
 */
abstract class GoldenSampleVarHandleArrayQueueColdField<E> extends ConcurrentCircularVarHandleArrayQueue<E>
{
    final int lookAheadStep;

    GoldenSampleVarHandleArrayQueueColdField(int capacity)
    {
        super(capacity);
        lookAheadStep = capacity / 4;
    }
}

/**
 * NOTE: This class was automatically generated by org.jctools.queues.varhandle.JavaParsingVarHandleArrayQueueGenerator
 * which can found in the jctools-build module. The original source file is GoldenSampleArrayQueue.java.
 */
abstract class GoldenSampleVarHandleArrayQueueL1Pad<E> extends GoldenSampleVarHandleArrayQueueColdField<E>
{
    byte b000,b001,b002,b003,b004,b005,b006,b007;//  8b
    byte b010,b011,b012,b013,b014,b015,b016,b017;// 16b

    GoldenSampleVarHandleArrayQueueL1Pad(int capacity)
    {
        super(capacity);
    }
}

/**
 * NOTE: This class was automatically generated by org.jctools.queues.varhandle.JavaParsingVarHandleArrayQueueGenerator
 * which can found in the jctools-build module. The original source file is GoldenSampleArrayQueue.java.
 */
abstract class GoldenSampleVarHandleArrayQueueProducerIndexFields<E> extends GoldenSampleVarHandleArrayQueueL1Pad<E>
{
    private static final VarHandle VH_PRODUCER_INDEX;
    
    static {
        try {
            VH_PRODUCER_INDEX = MethodHandles.lookup().findVarHandle(GoldenSampleVarHandleArrayQueueProducerIndexFields.class, "producerIndex", long.class);
        } catch (Exception e) {
            throw new ExceptionInInitializerError(e);
        }
    }
    
    private long producerIndex;
    protected long producerLimit;

    GoldenSampleVarHandleArrayQueueProducerIndexFields(int capacity)
    {
        super(capacity);
    }

    @Override
    public final long lvProducerIndex()
    {
        return (long) VH_PRODUCER_INDEX.getVolatile(this);
    }

    final long lpProducerIndex()
    {
        return producerIndex;
    }

    final void soProducerIndex(final long newValue)
    {
        VH_PRODUCER_INDEX.setRelease(this, newValue);
    }

    final boolean casProducerIndex(long expect, long newValue)
    {
        return VH_PRODUCER_INDEX.compareAndSet(this, expect, newValue);
    }
}

/**
 * NOTE: This class was automatically generated by org.jctools.queues.varhandle.JavaParsingVarHandleArrayQueueGenerator
 * which can found in the jctools-build module. The original source file is GoldenSampleArrayQueue.java.
 *
 * Pre-existing Javadoc on the public class — the generator must prepend its NOTE without
 * dropping this content.
 */
public class GoldenSampleVarHandleArrayQueue<E> extends GoldenSampleVarHandleArrayQueueProducerIndexFields<E>
{
    static int sentinel;
    // Unrelated static initializer — must survive the Unsafe-cleanup pass.
    static
    {
        sentinel = 42;
    }

    public GoldenSampleVarHandleArrayQueue(final int capacity)
    {
        super(capacity);
    }

    @Override
    public boolean offer(final E e)
    {
        if (null == e)
        {
            throw new NullPointerException();
        }
        final E[] buffer = this.buffer;
        final long mask = this.mask;
        final long pIndex = this.lpProducerIndex();
        final long offset = calcCircularRefElementOffset(pIndex, mask);
        soRefElement(buffer, offset, e);
        soProducerIndex(pIndex + 1);
        return true;
    }

    @Override
    public E poll()
    {
        return null;
    }

    public final int failFastOffer(final E e)
    {
        return 0;
    }
    
    /**
     * @deprecated This was renamed to failFastOffer please migrate
     */
    @Deprecated
    public int weakOffer(E e) {
        return this.failFastOffer(e);
    }

}
